### ISSUE TITLE
xs:qname enumerations are evaluated as string

### ISSUE THREAD

**Issue by tefra** [sissaschool/xmlschema#183]
Enumerations with xs:qname base are evaluated as simple strings and not properly through their real namespace. This is causing instances with custom namespaces prefixes or without target namespaces to fail.

From the w3c test suite take this definition
`nistData/atomic/QName/Schema+Instance/NISTSchema-SV-IV-atomic-QName-enumeration-5.xsd`

The original instance from the test group

```xml
<NISTSchema-SV-IV-atomic-QName-enumeration-5
    xmlns="NISTSchema-SV-IV-atomic-QName-enumeration-5-NS"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="NISTSchema-SV-IV-atomic-QName-enumeration-5-NS NISTSchema-SV-IV-atomic-QName-enumeration-5.xsd"
>_for-files.supply.for.to-must_measur</NISTSchema-SV-IV-atomic-QName-enumeration-5>
```

A modified version with custom prefixes fails

```xml
<ns0:NISTSchema-SV-IV-atomic-QName-enumeration-5 
    xmlns:ns0="NISTSchema-SV-IV-atomic-QName-enumeration-5-NS" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">ns0:_for-files.supply.for.to-must_measur</ns0:NISTSchema-SV-IV-atomic-QName-enumeration-5>
```

The difference is that the target namespace is added with the prefix **ns0**

**Comment by brunato** [comment]
Hi,
ok, mapping can be resolved in `iter_decode()` and `iter_encode()` methods of atomic types (`simple_types.py` module).
I'll inform when the fix is available.
Thanks

**Comment by brunato** [comment]
Hi,
fixed with release v1.1.3.
Thank you

**Comment by tefra** [comment]
Hi @brunato, it still fails for me with v.1.1.3

same example
`nistData/atomic/QName/Schema+Instance/NISTSchema-SV-IV-atomic-QName-enumeration-5.xsd`

```xml
<ns0:NISTSchema-SV-IV-atomic-QName-enumeration-5 
xmlns:ns0="NISTSchema-SV-IV-atomic-QName-enumeration-5-NS" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">ns0:_for-files.supply.for.to-must_measur</ns0:NISTSchema-SV-IV-atomic-QName-enumeration-5>

```

**Comment by brunato** [comment]
Hi @tefra,
 
sorry, I had forgot to include the default namespace case. Fixed now, will be included in the next release.

**Comment by brunato** [comment]
Fix available, 
Best
